export const STYLE_KEYS = [
  'color',
  'backgroundColor',
  'fontSize',
  'fontWeight',
  'fontFamily',
  'lineHeight',
  'fontStyle',
  'letterSpacing',
  'textDecoration',
  'textTransform',
  'whiteSpace',
  'height',
  'display',
  'position',
  'top',
  'right',
  'bottom',
  'left',
  'zIndex',
  'opacity',
  'overflow',
  'float',
  'borderRadius',
  'borderWidth',
  'borderStyle',
  'borderColor',
  'padding',
  'marginTop',
  'marginLeft',
  'widthPercent',
  'textAlign',
]

export const HISTORY_LIMIT = 50

export function createDefaultStyleForm() {
  return {
    color: '#111111',
    backgroundColor: '#ffffff',
    fontSize: 16,
    fontWeight: '',
    fontFamily: '',
    lineHeight: '',
    fontStyle: '',
    letterSpacing: '',
    textDecoration: '',
    textTransform: '',
    whiteSpace: '',
    height: '',
    display: '',
    position: '',
    top: '',
    right: '',
    bottom: '',
    left: '',
    zIndex: '',
    opacity: '',
    overflow: '',
    float: '',
    borderRadius: 0,
    borderWidth: 0,
    borderStyle: '',
    borderColor: '#000000',
    padding: 0,
    marginTop: 0,
    marginLeft: 0,
    widthPercent: 100,
    textAlign: '',
  }
}
